CREATE TABLE IF NOT EXISTS rbac_realms (
  id VARCHAR(100) NOT NULL PRIMARY KEY,
  description TEXT NOT NULL,
  created_by VARCHAR(36),
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_by VARCHAR(36),
  updated_at TIMESTAMP  NOT NULL DEFAULT CURRENT_TIMESTAMP
);

INSERT INTO rbac_realms VALUES('default', 'Default Realm', 'SEEDED', CURRENT_TIMESTAMP, 'SEEDED', CURRENT_TIMESTAMP);
